app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField, DecimalField
from wtforms.validators import Required, Email, Length, DataRequired, NumberRange
from flask_wtf.file import FileField, FileRequired, FileAllowed
from werkzeug.utils import secure_filename


class SeasonForm(FlaskForm):
    code = StringField('Season Code', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Season Code"})
    name = StringField('Season Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Season Name"})

class FactoryForm(FlaskForm):
    code = StringField('Factory Code', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Factory Code"})
    name = StringField('Factory Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Factory Name"})

class ProduceForm(FlaskForm):
    code = StringField('Produce Code', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Produce Code"})
    name = StringField('Produce Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Produce Name"})
    cess = StringField('KDB Cess', validators=[Required()], render_kw={"placeholder": "Kenya Dairy Board Cess"})

class RouteForm(FlaskForm):
    code = StringField('Route Code', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Route Code"})
    name = StringField('Route Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Route Name"})


class CentreForm(FlaskForm):
    code = StringField('Centre Code', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Centre Code"})
    name = StringField('Centre Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Centre Name"})
    route = SelectField('Route:', validators=[Required()], id='select_route',  coerce=int)


class FarmersForm(FlaskForm):
    supplier_no = StringField('Supplier No', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Supplier/Farmer No"})
    first_name = StringField('First Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "First Name"})
    last_name = StringField('Last Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Last Name"})
    id_number = StringField('ID No', validators=[Required()], render_kw={"placeholder": "National ID No"})
    phone_number = StringField('Phone Number', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Phone Number"})
    centre = SelectField('Station:', validators=[Required()], id='select_station',  coerce=int)

class FarmersUploadForm(FlaskForm):
    farmers_csv = FileField('farmers_csv', validators=[FileAllowed(['csv'], 'Upload CSV Files only!')])


class ContractForm(FlaskForm):
    produce = SelectField('Produce:', validators=[Required()], id='select_produce',  coerce=int)
    factory = SelectField('Factory:', validators=[Required()], id='select_factory',  coerce=int)
    price = StringField('Price', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Price per KG"})
    payment_term = SelectField(u'Payment Term', choices=[('WK', 'Weekly'), ('MN', 'Monthly'), ('DL', 'Daily')])


class VehicleForm(FlaskForm):
    reg_no = StringField('Reg No', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Reg No"})
    make = StringField('Make', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Make"})
    body = StringField('Body', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Body"})
    color = StringField('Color', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Color"})
    ownership = SelectField(u'Ownership', choices=[('HCF', 'Highlands Creameries & Foods'), ('HRD', 'Hired')])

class GraderForm(FlaskForm):
    first_name = StringField('First Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "First Name"})
    last_name = StringField('Last Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Last Name"})
    phone_number = StringField('Phone Number', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Phone Number"})
    app_username = StringField('App Username', validators=[Required(), Length(1,64)], render_kw={"placeholder": "App Username"})
    app_password = StringField('App Password', validators=[Required(), Length(1,64)], render_kw={"placeholder": "App Password"})
    role = SelectField('Role:', validators=[Required()], id='select Role',  coerce=int)

class TripForm(FlaskForm):
    trip_date = StringField('Trip Date:', validators=[Required()], id='datetimepicker1')
    route = SelectField('Route:', validators=[Required()], id='select route',  coerce=int)
    grader = SelectField('Grader:', validators=[Required()], id='select grader',  coerce=int)
    driver = SelectField('Driver:', validators=[Required()], id='select driver',  coerce=int)
    vehicle = SelectField('Vehicle:', validators=[Required()], id='select vehicle',  coerce=int)
    


class CompleteTripForm(FlaskForm):
     total_weight_received = StringField('Total Kgs Received', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Total Kgs Received at the factory"})
    


class DriverForm(FlaskForm):
    first_name = StringField('First Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "First Name"})
    last_name = StringField('Last Name', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Last Name"})
    phone_number = StringField('Phone Number', validators=[Required(), Length(1,64)], render_kw={"placeholder": "Phone Number"})

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for, flash, request, current_app
from flask_login import login_required, current_user
from .forms import FarmersUploadForm, FactoryForm, CentreForm, ProduceForm, FarmersForm, SeasonForm, ContractForm, RouteForm,VehicleForm, GraderForm, DriverForm, TripForm, CompleteTripForm
from ..models import Factory, CollectionCentre, Produce, Farmer, Season, Collection, FarmerContract, Route, Vehicle, AppUser, Role, Driver, Trip, TripPayment
from app import db
from werkzeug.utils import secure_filename
import os
import uuid
import re
import csv


from . import main

@main.route('/', methods=['GET', 'POST'])
@login_required
def index():
    # LECH CODE HERE
    farmer_count = Farmer.query.count()
    graders_count = AppUser.query.count()
    routes_count = Route.query.count()
    centre_count = CollectionCentre.query.count()
    return render_template('main/dashboard.html', centre_count=centre_count, farmers_count=farmer_count, graders_count=graders_count, routes_count=routes_count)


@main.route('/factories', methods=['GET', 'POST'])
@login_required
def factories():
    factories = Factory.query.all()
    return render_template('main/factories.html', factories=factories)


@main.route('/new-factory', methods=['GET', 'POST'])
@login_required
def new_factory():
    form = FactoryForm()
    if form.validate_on_submit():
        factory = Factory(code=form.code.data, name=form.name.data, creator=current_user)
        db.session.add(factory)
        db.session.commit()
        flash('The factory was added successfully.', 'success')
        return redirect(url_for('.factories'))
    return render_template('main/new_factory.html', form=form)


@main.route('/factory/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_factory(id):
    factory = Factory.query.get_or_404(id)
    form = FactoryForm()
    form.code.data = factory.code
    form.name.data = factory.name
    if form.validate_on_submit():
        factory.code = request.form.get('code')
        factory.name = request.form.get('name')
        db.session.add(factory)
        db.session.commit()
        flash('The factory was updated successfully.', 'success')
        return redirect(url_for('.factories'))
    return render_template('main/new_factory.html', form=form)

@main.route('/seasons', methods=['GET', 'POST'])
@login_required
def seasons():
    seasons = Season.query.all()
    return render_template('main/seasons.html', seasons=seasons)


@main.route('/new-season', methods=['GET', 'POST'])
@login_required
def new_season():
    form = SeasonForm()
    if form.validate_on_submit():
        season = Season(code=form.code.data, name=form.name.data, creator=current_user)
        db.session.add(season)
        db.session.commit()
        flash('The season was added successfully.', 'success')
        return redirect(url_for('.seasons'))
    return render_template('main/new_season.html', form=form)
    


@main.route('/produce', methods=['GET', 'POST'])
@login_required
def produce():
    produce = Produce.query.all()
    return render_template('main/produce.html', produce=produce)


@main.route('/new-produce', methods=['GET', 'POST'])
@login_required
def new_produce():
    form = ProduceForm()
    if form.validate_on_submit():
        produce = Produce(code=form.code.data, name=form.name.data, creator=current_user, cess=form.cess.data)
        db.session.add(produce)
        db.session.commit()
        flash('The Produce was added successfully.', 'success')
        return redirect(url_for('.produce'))
    return render_template('main/new_produce.html', form=form)


@main.route('/produce/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_produce(id):
    produce = Produce.query.get_or_404(id)
    form = ProduceForm()
    form.code.data = produce.code
    form.name.data = produce.name
    form.cess.data = produce.cess
    if form.validate_on_submit():
        produce.code = request.form.get('code')
        produce.name = request.form.get('name')
        produce.cess = request.form.get('cess')
        db.session.add(produce)
        db.session.commit()
        flash('The produce was updated successfully.', 'success')
        return redirect(url_for('.produce'))
    return render_template('main/new_produce.html', form=form)



@main.route('/centres', methods=['GET', 'POST'])
@login_required
def centres():
    centres = CollectionCentre.query.all()
    return render_template('main/centres.html', centres=centres)


@main.route('/routes', methods=['GET', 'POST'])
@login_required
def routes():
    routes = Route.query.all()
    return render_template('main/routes.html', routes=routes)


@main.route('/new-route', methods=['GET', 'POST'])
@login_required
def new_route():
    form = RouteForm()
    if form.validate_on_submit():
        route = Route(code=form.code.data, name=form.name.data, creator=current_user)
        db.session.add(route)
        db.session.commit()
        flash('Route was added successfully.', 'success')
        return redirect(url_for('.routes'))
    return render_template('main/new_route.html', form=form)


@main.route('/route/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_route(id):
    route = Route.query.get_or_404(id)
    form = RouteForm()
    form.code.data = route.code
    form.name.data = route.name
    if form.validate_on_submit():
        route.code = request.form.get('code')
        route.name = request.form.get('name')
        db.session.add(route)
        db.session.commit()
        flash('The route was updated successfully.', 'success')
        return redirect(url_for('.routes'))
    return render_template('main/new_route.html', form=form)



@main.route('/new-vehicle', methods=['GET', 'POST'])
@login_required
def new_vehicle():
    form = VehicleForm()
    if form.validate_on_submit():
        vehicle = Vehicle(reg_no=form.reg_no.data, make=form.make.data, ownership=form.ownership.data, color=form.color.data, body=form.body.data, creator=current_user)
        db.session.add(vehicle)
        db.session.commit()
        flash('Motor Vehicle added successfully.', 'success')
        return redirect(url_for('.vehicles'))
    return render_template('main/new_vehicle.html', form=form)


@main.route('/vehicle/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_vehicle(id):
    vehicle = Vehicle.query.get_or_404(id)
    form = VehicleForm()
    form.reg_no.data = vehicle.reg_no
    form.make.data = vehicle.make
    form.ownership.data = vehicle.ownership
    form.color.data = vehicle.color
    form.body.data = vehicle.body
    if form.validate_on_submit():
        vehicle.reg_no = request.form.get('reg_no')
        vehicle.make = request.form.get('make')
        vehicle.ownership = request.form.get('ownership')
        vehicle.color = request.form.get('color')
        vehicle.body = request.form.get('body')
        db.session.add(vehicle)
        db.session.commit()
        flash('The vehicle was updated successfully.', 'success')
        return redirect(url_for('.vehicles'))
    return render_template('main/new_vehicle.html', form=form)


@main.route('/vehicles', methods=['GET', 'POST'])
@login_required
def vehicles():
    vehicles = Vehicle.query.all()
    return render_template('main/vehicles.html', vehicles=vehicles)


@main.route('/graders', methods=['GET', 'POST'])
@login_required
def graders():
    objects = AppUser.query.all()
    return render_template('main/graders.html', objects=objects)


@main.route('/new_grader', methods=['GET', 'POST'])
@login_required
def new_grader():
    form = GraderForm()
    form.role.choices = [(row.id, row.name) for row in Role.query.all()]
    if form.validate_on_submit():
        grader = AppUser(
                first_name=form.first_name.data, 
                last_name=form.last_name.data, 
                phone_number=form.phone_number.data, 
                username=form.app_username.data, 
                app_password=form.app_password.data, 
                creator=current_user,
                role_id = form.role.data
            )
        db.session.add(grader)
        db.session.commit()
        flash('Grader added successfully.', 'success')
        return redirect(url_for('.graders'))
    return render_template('main/new_grader.html', form=form)



@main.route('/grader/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_grader(id):
    grader = AppUser.query.get_or_404(id)
    form = GraderForm(role=grader.role_id)
    form.first_name.data = grader.first_name
    form.last_name.data = grader.last_name
    form.phone_number.data = grader.phone_number
    form.app_username.data = grader.username
    form.app_password.data = grader.app_password
    form.role.choices = [(row.id, row.name) for row in Role.query.all()]
    if form.validate_on_submit():
        grader.first_name = request.form.get('first_name')
        grader.last_name = request.form.get('last_name')
        grader.phone_number = request.form.get('phone_number')
        grader.username = request.form.get('app_username')
        grader.app_password = request.form.get('app_password')
        grader.role_id = request.form.get('role')
        db.session.add(grader)
        db.session.commit()
        flash('The grader was updated successfully.', 'success')
        return redirect(url_for('.graders'))
    return render_template('main/new_grader.html', form=form)


@main.route('/grader/<int:id>/trips', methods=['GET', 'POST'])
@login_required
def grader_trips(id):
    grader = AppUser.query.get_or_404(id)
    objects = Trip.query.filter_by(grader_id=grader.id)
    return render_template('main/grader_trips.html', objects=objects, grader=grader)

@main.route('/driver/<int:id>/trips', methods=['GET', 'POST'])
@login_required
def driver_trips(id):
    driver = Driver.query.get_or_404(id)
    objects = Trip.query.filter_by(driver_id=driver.id) # SELECT * FROM TRIPS WHERE driver_id = 121

app/templates/main/dashboard.html
{% extends "base.html" %}

{% block page_content %}
<div class="right_col" role="main">
	<div class="">
		<div class="row top_tiles">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats  panel panel-primary">
                  <div class="icon"><i class="fa fa-group"></i></div>
                  <div class="count label label-success">&nbsp;{{farmers_count}} &nbsp;</div>
                  <h3 class="">Farmers</h3>
                  <p>Total Number of farmers.</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-user"></i></div>
                  <div class="count label label-warning">&nbsp;{{graders_count}} &nbsp;</div>
                  <h3>Graders</h3>
                  <p>Total Number of graders.</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-arrows-alt"></i></div>
                  <div class="count label label-primary">&nbsp;{{routes_count}} &nbsp;</div>
                  <h3>Routes</h3>
                  <p>Total Number of routes</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-universitys"></i></div>
                  <div class="count label label-danger">&nbsp;{{centre_count}} &nbsp;</div>
                  <h3>Centres</h3>
                  <p>Total number of centres</p>
                </div>
              </div>
            </div>

            
	</div>
</div>
{% endblock %}

app/templates/main/factories.html
{% extends "base.html" %}

{% block page_title %}
	Factories
{% endblock %}


{% block extra_css %}
	<link href="{{url_for('static', filename='libs/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='libs/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='libs/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='libs/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='libs/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')}}" rel="stylesheet">
{% endblock %}

{% block page_content %}
	        <div class="right_col" role="main">
          <div class="">

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Factories</h2>
                    <a href="{{url_for('main.new_factory')}}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> New Factory</a>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  <p>
                  	{% with messages = get_flashed_messages(with_categories=true)  %}

            {% if messages %}

              {% for type, message in messages %}

                  <div class="alert alert-{{type}} alert-dismissible fade in" role="alert">
                    <strong>{{type|title}}!</strong> {{message}}.
                  </div>

              {% endfor %}

            {% endif %}

          {% endwith %}
                  </p>
                  {% if factories %}
                  	<table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Code</th>
                          <th>Name</th>
                          <th>Added On</th>
                          <th>Added By</th>
                          <th>Actions</th>
                        </tr>
                      </thead>


                      <tbody>
                  {% for factory in factories %}
                  	<tr>
                          <td>{{factory.id}}</td>
                          <td>{{factory.code}}</td>
                          <td>{{factory.name}}</td>
                          <td>{{factory.draft_date}}</td>
                          <td>{{factory.creator}}</td>
                          <td>
                            <!-- <a href="#" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a> -->
                            <a href="{{ url_for('main.edit_factory', id=factory.id) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                          </td>
                        </tr>
                  {% endfor %}

                   </tbody>
                    </table>
                  	
                  {% endif %}
                   
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block extra_js %}
	<script src="{{url_for('static', filename='libs/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-scroller/js/dataTables.scroller.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/jszip/dist/jszip.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/pdfmake/build/pdfmake.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/pdfmake/build/vfs_fonts.js')}}"></script>
{% endblock %}

app/templates/main/new_centre.html
{% extends "base.html" %}

{% block page_title %}
	New Station
{% endblock %}


{% block page_content %}
	        <div class="right_col" role="main">
          <div class="">

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  
                  <div class="x_title">
                    <h2>New Station<small> Capture new members station/Collection Centre</small></h2>
                    <a href="{{url_for('main.factories')}}" class="btn btn-primary pull-right"><i class="fa fa-history"></i> Back </a>
                    <div class="clearfix"></div>
                  </div>
                  
                  <div class="x_content">


                    
                    <form action="" method="post" class="form-horizontal form-label-left">
                    {{ form.csrf_token }}
                    

                    <div class="form-group {% if form.code.errors %} has-error {% endif %}">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ form.code.label }} <span class="required">*</span></label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                         {{ form.code(class_="form-control col-md-7 col-xs-12") }}
                         {% if form.code.errors %}
                            <span class="help-block"></span>
                            <span id="helpBlock2" class="help-block">{{ form.code.errors[0] }}</span>
                        {% endif %}
                      </div>
                    </div>

                    <div class="form-group {% if form.name.errors %} has-error {% endif %}">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ form.name.label }} <span class="required">*</span></label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                         {{ form.name(class_="form-control col-md-7 col-xs-12") }}
                         {% if form.name.errors %}
                            <span class="help-block"></span>
                            <span id="helpBlock2" class="help-block">{{ form.name.errors[0] }}</span>
                        {% endif %}
                      </div>
                    </div>


                    <div class="form-group {% if form.route.errors %} has-error {% endif %}">
                      <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">{{ form.route.label }} <span class="required">*</span></label>
                      <div class="col-md-6 col-sm-6 col-xs-12">
                         {{ form.route(class_="form-control col-md-7 col-xs-12") }}
                         {% if form.route.errors %}
                            <span class="help-block"></span>
                            <span id="helpBlock2" class="help-block">{{ form.route.errors[0] }}</span>
                        {% endif %}
                      </div>
                    </div>

                
                    <div class="ln_solid"></div>
                    <div class="form-group">
                      <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <button class="btn btn-primary" type="button">Cancel</button>
                    <button class="btn btn-primary" type="reset">Reset</button>
                        <button type="submit" class="btn btn-success">Submit</button>
                      </div>
                    </div>
                    </form>


                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

app/templates/main/vehicles.html
{% extends "base.html" %}

{% block page_title %}
	Motor Vehicles
{% endblock %}


{% block extra_css %}
	<link href="{{url_for('static', filename='libs/datatables.net-bs/css/dataTables.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='libs/datatables.net-buttons-bs/css/buttons.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='libs/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='libs/datatables.net-responsive-bs/css/responsive.bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{url_for('static', filename='libs/datatables.net-scroller-bs/css/scroller.bootstrap.min.css')}}" rel="stylesheet">
{% endblock %}

{% block page_content %}
	        <div class="right_col" role="main">
          <div class="">

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Motor Vehicles</h2>
                    <a href="{{url_for('main.new_vehicle')}}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> New Vehicle</a>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  <p>
                  	{% with messages = get_flashed_messages(with_categories=true)  %}

            {% if messages %}

              {% for type, message in messages %}

                  <div class="alert alert-{{type}} alert-dismissible fade in" role="alert">
                     {{message}}.
                  </div>

              {% endfor %}

            {% endif %}

          {% endwith %}
                  </p>
                  {% if vehicles %}
                  	<table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>Reg No</th>
                          <th>Make</th>
                          <th>Body</th>
                          <th>Color</th>
                          <th>Ownership</th>
                          <th>Actions</th>
                        </tr>
                      </thead>


                      <tbody>
                  {% for vehicle in vehicles %}
                  	<tr>
                          <td>{{vehicle.reg_no}}</td>
                          <td>{{vehicle.make}}</td>
                          <td>{{vehicle.body}}</td>
                          <td>{{vehicle.color}}</td>
                          <td>{{vehicle.ownership}}</td>
                          <td><a href="{{url_for('main.edit_vehicle', id=vehicle.id)}}" class="btn btn-info btn-xs pull-right"><i class="fa fa-eye"></i> Edit Vehicle</a></td>
                        </tr>
                  {% endfor %}

                   </tbody>
                    </table>
                  	
                  {% endif %}
                   
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

{% block extra_js %}
    <script src="{{url_for('static', filename='libs/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-keytable/js/dataTables.keyTable.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-responsive-bs/js/responsive.bootstrap.js')}}"></script>
    <script src="{{url_for('static', filename='libs/datatables.net-scroller/js/dataTables.scroller.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/jszip/dist/jszip.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/pdfmake/build/pdfmake.min.js')}}"></script>
    <script src="{{url_for('static', filename='libs/pdfmake/build/vfs_fonts.js')}}"></script>
{% endblock %}